// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN5VCNXx1r51hKOaKMn1xyLUmzaCOoWAE',
    appId: '1:143563591060:web:96209ae3fbb36d35b7d381',
    messagingSenderId: '143563591060',
    projectId: 'safe-route-2fb79',
    authDomain: 'safe-route-2fb79.firebaseapp.com',
    storageBucket: 'safe-route-2fb79.firebasestorage.app',
    measurementId: 'G-DEG4CDVVT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7e3T24VT4q9rjhVknZdvS_hQGyhea8I',
    appId: '1:143563591060:android:3abb2660bad9a371b7d381',
    messagingSenderId: '143563591060',
    projectId: 'safe-route-2fb79',
    storageBucket: 'safe-route-2fb79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDWOFO59rRGFU5e1eEUxkGk01gVAgJVYY',
    appId: '1:143563591060:ios:68c40984e0bc1377b7d381',
    messagingSenderId: '143563591060',
    projectId: 'safe-route-2fb79',
    storageBucket: 'safe-route-2fb79.firebasestorage.app',
    iosBundleId: 'com.example.parentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDWOFO59rRGFU5e1eEUxkGk01gVAgJVYY',
    appId: '1:143563591060:ios:68c40984e0bc1377b7d381',
    messagingSenderId: '143563591060',
    projectId: 'safe-route-2fb79',
    storageBucket: 'safe-route-2fb79.firebasestorage.app',
    iosBundleId: 'com.example.parentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN5VCNXx1r51hKOaKMn1xyLUmzaCOoWAE',
    appId: '1:143563591060:web:b4cc1338b5d40097b7d381',
    messagingSenderId: '143563591060',
    projectId: 'safe-route-2fb79',
    authDomain: 'safe-route-2fb79.firebaseapp.com',
    storageBucket: 'safe-route-2fb79.firebasestorage.app',
    measurementId: 'G-8EJ79E6NR8',
  );
}